# Generated by Django 5.0.3 on 2024-03-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("edv", models.CharField(max_length=8, unique=True)),
                ("cargo", models.CharField(max_length=100)),
                ("setor", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("horario_entrada", models.TimeField()),
                ("horario_saida", models.TimeField()),
                ("data_admissao", models.DateField()),
            ],
        ),
    ]
