# Generated by Django 5.0.3 on 2024-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
                ("quantidade", models.IntegerField()),
                ("peso", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "voltagem",
                    models.CharField(
                        choices=[("110", "110"), ("220", "220")], max_length=10
                    ),
                ),
                ("marca", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
            ],
        ),
    ]
